Repository hzuapps/html5-2018, pull requests merged in 2018-11, with the labels that each got.

#359 #2 第二次实验
  1614080902419/2_1.png
  1614080902419/2_2.png
  1614080902419/images/Education.png
  1614080902419/images/PersonalIcon.png
  1614080902419/images/Practial.png
  1614080902419/images/Self.png
  1614080902419/images/arrows.png
  1614080902419/images/head.jpg
  1614080902419/images/skill.png
  1614080902419/resume.css
  1614080902419/resume.html
Labels: Late

#367 实验2
  1614080902340/1.html
  1614080902340/1.jpg
Labels: Late

#377 #2 实验2
  1614080902343/resume.html
  1614080902343/resume.jpg
Labels: Late

#407 实验1 实验2 实验3程序
  1614080902105/61511810_p0.jpg
  1614080902105/实验1.html
  1614080902105/实验2.html
  1614080902105/实验3.html
Labels: Late

#467 #4 第四次实验
  1614080902119/demo3.html
  1614080902119/demo4-1.html
Labels: Good

#470 #4 实验四
  1614080902341/code/jianLiUi.html
  1614080902341/code/jianliui.css
  1614080902341/code/jianliui.js
  1614080902341/img/bg0.jpg
  1614080902341/img/bg1.jpg
  1614080902341/img/bg2.jpg
  1614080902341/img/bg3.jpg
  1614080902341/img/bg4.jpg
Labels: Good

#473 #实验4 表单验证和改变背景颜色
  1612070501311/Lab4.css
  1612070501311/Lab4.html
  1612070501311/Lab4.js
  1612070501311/Lab4.png
  1612070501311/M_board.html
Labels: Good

#474 #4 第四次实验
  1614080902117/colorswitch.html
  1614080902117/resume-weui.html
Labels: Good

#475 #4 第四次实验form表单+背景改变
  1614080902212/mao.js
  1614080902212/mao3.html
  1614080902212/pass.html
Labels: Good

#551 #3 第三次实验
  1614080902336/Shiyan2.html
  1614080902336/Shiyan3.html
  1614080902336/实验3图片1.jpg
  1614080902336/实验3图片2.png
Labels: Late

#557 实验2，3，4
  1614080902146/M_board.html
  1614080902146/QQ.JPG
  1614080902146/assets/weui.min.css
  1614080902146/lab4.html
  1614080902146/lab4.js
  1614080902146/text1.html
  1614080902146/text2.html
  1614080902146/text3.html
Labels: Late

#558 #3 #第三次实验
  1614080902214/resume3.html
Labels: Late

#563 #2 实验2和实验3
  1614080902411/example.css
  1614080902411/example.js
  1614080902411/lab3.html
  1614080902411/weui.min.css
Labels: Late

#565 #3 第三次实验
  1614080902202/456.html
Labels: Late

#579 #3 实验三和实验四
  1614080902101/实验三.html
  1614080902101/实验四.html
  1614080902101/简历.html
Labels: Late

#582 第三次实验
  1614080902235/个人简历2.html
Labels: Late

#627 #3 第三次实验
  1614080902401/shiyan3/U4P1T52D145F1033DT20131105102009.jpg
  1614080902401/shiyan3/shiyan3.html
Labels: Late

#661 实验三
  1614080902324/weui简历.html
Labels: Late

#665 第四次实验
  1609081602618/README.md
  1609081602618/WEUI_resume.html
  1609081602618/jianli.html
  1609081602618/图片1.png
Labels: Late

#685 #3 第三次实验
  1614080902432/实验三/ACE.jpg
  1614080902432/实验三/index.html
  1614080902432/实验四/ACE.jpg
  1614080902432/实验四/index.html
Labels: Late

#703 #3 #4 实验三四
  1613071002206/#3实验3.html
  1613071002206/实验4.html
  1613071002206/实验4.png
Labels: Late

#714 713text
  1614080902222/text6/app.js
  1614080902222/text6/app.json
  1614080902222/text6/app.wxss
  1614080902222/text6/pages/index/img/equipment1.png
  1614080902222/text6/pages/index/img/equipment2.png
  1614080902222/text6/pages/index/img/mine1.png
  1614080902222/text6/pages/index/img/mine2.png
  1614080902222/text6/pages/index/img/newspaper1.png
  1614080902222/text6/pages/index/img/newspaper2.png
  1614080902222/text6/pages/index/index.js
  1614080902222/text6/pages/index/index.json
  1614080902222/text6/pages/index/index.wxml
  1614080902222/text6/pages/index/index.wxss
  1614080902222/text6/pages/logs/logs.js
  1614080902222/text6/pages/logs/logs.json
  1614080902222/text6/pages/logs/logs.wxml
  1614080902222/text6/pages/logs/logs.wxss
  1614080902222/text6/pages/tabOne/tabOne.js
  1614080902222/text6/pages/tabOne/tabOne.json
  1614080902222/text6/pages/tabOne/tabOne.wxml
  1614080902222/text6/pages/tabOne/tabOne.wxss
  1614080902222/text6/pages/tabTwo/tabTwo.js
  1614080902222/text6/pages/tabTwo/tabTwo.json
  1614080902222/text6/pages/tabTwo/tabTwo.wxml
  1614080902222/text6/pages/tabTwo/tabTwo.wxss
  1614080902222/text6/project.config.json
  1614080902222/text6/utils/util.js
Labels: Copy

#734 实验三
  1614080902412/1.html
Labels: Late

#753 #3 #4 实验三、四
  1614080902320/cv2.html
Labels: Late

#843 #4 Test4
  1614080902339/Resume-Test_4.html
Labels: Late

#847 #4 第四次实验+练习
  1614080902336/Index.js
  1614080902336/Lianxi.html
  1614080902336/Pass.html
  1614080902336/Shiyan4.html
  1614080902336/实验4图片1.png
  1614080902336/实验4图片2.png
Labels: Late

#871 #4 第四次实验
  1614080902202/NO4.html
Labels: Late

#888 #4 第四次实验
  1614080902204/images/myjmg.gif
Labels: Late

#913 #3 lab
  1614080902340/2.html
  1614080902340/2.jpg
  1614080902340/3.html
  1614080902340/3.jpg
  1614080902340/form.js
  1614080902340/pass.html
  1614080902340/截图1.PNG
  1614080902340/截图2.PNG
  1614080902340/截图3.PNG
  1614080902340/截图4.PNG
  1614080902340/截图5.PNG
  1614080902340/截图6.PNG
Labels: Late

#925 #3 第三次实验
  1614080902224/1.html
  1614080902224/2.html
Labels: Late

#950 #6 #949 第六次实验
  1614080902103/6/GIF.gif
  1614080902103/6/LICENSE
  1614080902103/6/README.md
  1614080902103/6/app.js
  1614080902103/6/app.json
  1614080902103/6/app.wxss
  1614080902103/6/pages/calc/calc.js
  1614080902103/6/pages/calc/calc.wxml
  1614080902103/6/pages/calc/calc.wxss
  1614080902103/6/pages/history/history.js
  1614080902103/6/pages/history/history.wxml
  1614080902103/6/pages/history/history.wxss
  1614080902103/6/pages/index/index.js
  1614080902103/6/pages/index/index.wxml
  1614080902103/6/pages/index/index.wxss
  1614080902103/6/pages/index/view.wxml
  1614080902103/6/pages/index/view.wxss
  1614080902103/6/pages/logs/logs.js
  1614080902103/6/pages/logs/logs.json
  1614080902103/6/pages/logs/logs.wxml
  1614080902103/6/pages/logs/logs.wxss
  1614080902103/6/project.config.json
  1614080902103/6/utils/util.js
Labels: Copy

#958 第三次实验
  1614080902210/resume-weui.html
Labels: Late

#983 #lab4
  1614080902411/lab4.html
  1614080902411/leaveMessage.html
Labels: Late

#988 #4第四次实验
  1614080902210/demo3.html
Labels: Late

#994 #4 实验四
  1614080902416/WeUIresume.html
Labels: Late

#1018 #4 第四次实验
  1614080902209/PersonalIntroduction.html
  1614080902209/pass.html
Labels: Late
